// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage;
using Microsoft.EntityFrameworkCore.Storage.Internal;
using SiteMonitor.Data.DbContexts;
using System;

namespace SiteMonitor.Migrations.AppDataDb
{
    [DbContext(typeof(AppDataDbContext))]
    partial class AppDataDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.0.1-rtm-125")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("SiteMonitor.Models.Site", b =>
                {
                    b.Property<int>("SiteId")
                        .ValueGeneratedOnAdd();

                    b.Property<TimeSpan>("CheckOnlineTimespan");

                    b.Property<DateTime>("LastCheck");

                    b.Property<string>("Name");

                    b.Property<bool>("SiteAvailability");

                    b.Property<string>("UriString");

                    b.HasKey("SiteId");

                    b.ToTable("Sites");
                });
#pragma warning restore 612, 618
        }
    }
}
